//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBFPTBOOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int AuthID { get; set; }
        public string AuthName { get; set; }
        public string Address { get; set; }
        public string AuthDesc { get; set; }
        public string Phone { get; set; }
    
        public virtual BookWriter BookWriter { get; set; }
    }
}
