//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBFPTBOOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookWriter
    {
        public int AuthID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Role { get; set; }
        public string Position { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
