//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBFPTBOOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string BookDesc { get; set; }
        public string BookPic { get; set; }
        public Nullable<System.DateTime> DayUpdate { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> PubID { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
